export { default as SignUp } from "./signUp/SignUp";
export { default as SignIn } from "./signIn/SignIn";
export { default as Form } from "./form/Form";
export { default as SignInForm } from "./signInForm/SignInForm";
export { default as Dashboard } from "./dashboard/Dashboard";
export { default as ForgotPassword } from "./forgotPassword/ForgotPassword";
export { default as ForgotPasswordForm } from "./ForgotPasswordForm/ForgotPasswordForm";
export { default as ResetPassword } from "./resetPassword/ResetPassword";
export { default as ResetPasswordForm } from "./resetPasswordForm/ResetPasswordForm"